# site properties and page defaults
title: MACHINE LEARNING AND COMPUTER VISION LAB
subtitle: FACULTY OF COMPUTER SCIENCE, UNIVERSITAS INDONESIA
description: The MLCV Lab focuses on machine learning-related research, especially for computer vision tasks that involve manipulating, analyzing, and interpreting data from images and videos. The methods used are diverse, from processing detailed information stored at the pixel level to geometrically dividing images into several regions to form highly correlated patterns for a specific task.
header: images/active_banner_720_15fps.gif
footer: images/active_banner_720_15fps.gif
# footer: images/background.jpg
# header-dark: false
# footer-dark: false
proofer: false

# site social media and other links
links:
  email: mlcvlab@cs.ui.ac.id
  github: MLCV-Lab-Fasilkom-UI
  # orcid: 0000-0001-8713-9213
  # google-scholar: ETJoidYAAAAJ
  # twitter: mlcvlab-fasilkom-ui
  # youtube: mlcvlab-fasilkom-ui

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
